### ISSUE TITLE
Unspash URL is not https

### ISSUE THREAD

**Issue by RickR2H** [Jakobud/vscode-placeholder-images#2]
Hi,

Thanks for this great extension!

I notices that the Unsplash URL's are created with prefix http and not https resulting in mixed content errors. I fixed it in my own installation for now, but a fix would be greatly appreciated.

Regards!

**Comment by Jakobud** [comment]
Thanks. I really should provide a user setting for specifying if you want to use `http`, `https` or protocol-less urls (`//`)

**Comment by RickR2H** [comment]
That would be a great option! Hopefully you'll find some time to implement the option.

Thanks in advance!

**Comment by KasperAndersson** [comment]
@Jakobud Would be a nice, option, but kinda rather just have hardcoded `https://`, why would you ever prefer `http://` ?

**Comment by Jakobud** [comment]
That is a good point. I did find at least 1 of the image services don't offer an https option, which is kind of odd. I'll be making this update soon. 

I've been working on making a lot of improvements to this extension. Adding quite a few services and as well as removing a few that are no longer around. Also added in the https change.

**Comment by RickR2H** [comment]
@Jakobud
